# Generated by Django 4.1.2 on 2022-10-24 22:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('categoria', models.CharField(choices=[('Outras', 'Outras'), ('Alimentação', 'Alimentação'), ('Saúde', 'Saúde'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Imprevistos', 'Imprevistos')], default='Outras', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
